version: '3.4'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  tpapp1:
    image: tpapp
    environment:
      - VIRTUAL_HOST=m

  tpapp2:
    image: tpapp
    environment:
      - VIRTUAL_HOST=m

  tpapp3:
    image: tpapp
    environment:
      - VIRTUAL_HOST=m

  tpapp4:
    image: tpapp
    environment:
      - VIRTUAL_HOST=m
